app:
  name: "Microkube"
  domain: "app.local"
  subdomain: "www"
ssl:
  enabled: false    # Make sure to enable during deployment
  email: "support@example.com"
images:
  peatio: rubykube/peatio:2.2.25
  barong: rubykube/barong:2.2.22
  frontend: gcr.io/openware-production/baseapp:2.2.18
  tower: gcr.io/openware-production/tower:2.2.8
  postmaster: quay.io/openware/postmaster:2.2.2
  applogic: rubykube/applogic:latest
  components-docs: gcr.io/openware-production/components-docs:latest
  arke: rubykube/arke:0.1.9
vendor:
  frontend: git@github.com:openware/baseapp.git
storage:
  provider: "Google"
  bucketName: "microkube-barong-docs-bucket"
  accessKey: "**********"
  secretKey: "**********"
terraform:
  credentials: "~/safe/microkube.json"
  project: "example-microkube"
  region: "europe-west4"
  zone: "europe-west4-a"
  instance_name: "microkube-cloud"
  machine_type: "n1-standard-4"
  image: "debian-cloud/debian-9"
twilio:
  phone_number: "+15005550000"
  account_sid: "changeme"
  auth_token: "changeme"
recaptcha:
  type: "none"
  siteKey: "changeme"
  secretKey: "changeme"
smtp:
  host: smtp.sendgrid.net
  port: 2525
  user: apikey
  password: changeme
  sender_email: noreply@postmaster.com
  sender_name: Postmaster
wallets:
  - kind: deposit
    address: "changeme"
    nsig: 1
    max_balance: 0.0
    secret: changeme
  - kind: hot
    address: "changeme"
    nsig: 1
    max_balance: 100.0
    secret: changeme
  - kind: warm
    address: "changeme"
    nsig: 1
    max_balance: 1000.0
    secret: changeme
superset:
  email: superset-admin@openware.com
  username: admin
  password: changeme
tenko:
  url: "https://www.openware.com/api/v2/tenko"
arke:
  strategy:
    type: copy
    volume_ratio: 0.1
    target:
      driver: rubykube
      market: 'FTHUSD'
      host: "http://www.app.local"
      key: ""
      secret: ""
      rate_limit: 1
    sources:
      - driver: bitfaker
        market: 'tETHUSD'
        host: "api.bitfinex.com"
        key: ""
        secret: ""
        rate_limit: 0.2
      - driver: bitfinex
        market: 'tETHUSD'
        host: "api.bitfinex.com"
        key: ""
        secret: ""
        rate_limit: 0.2
      - driver: binance
        market: 'ETHUSDT'
        host: "api.binance.com"
        key: ""
        secret: ""
        rate_limit: 0.2
