---
app:
  name: OpenDAX
  domain: app.local
  subdomain: www
  show_landing: true
render_protect: false
csrfEnabled: false
ssl:
  enabled: false
  email: support@example.com
updateVersions: false
images:
  peatio: quay.io/openware/peatio:2.6.0-8f4311c
  barong: quay.io/openware/barong:2.6.0-c563225
  sonic: quay.io/openware/baseapp:2.6.0-e1bcbaae
  tower: quay.io/openware/tower:3.0.0-ccde1dd
  rango: quay.io/openware/rango:2.6.0-1ecb85b
  finex: quay.io/openware/openfinex:2.7.0-3acdefe
vendor:
  frontend: git@github.com:openware/baseapp.git
kyc:
  provider: local
  authorization_token: changeme
  sandbox_mode: true
  api_endpoint: https://api.kycaid.com/
vault:
  root_token: s.NF3MIv5PFWlKPrg6b2UPUwwt
  peatio_rails_token: s.hrQaHB4UXbnkBGQhZnV1L4dx
  peatio_crypto_token: s.T1IDoGz8Yi5Wn2pzRQCrEq5D
  peatio_upstream_token: s.RC3fpdNkPazAeQDOZCui9Toc
  peatio_matching_token: s.zYUCX6yVieLhGFK0uLY1VHtH
  barong_token: s.iEfWex9bCYz9hxeh4kcWHaDK
  finex_engine_token: s.e5wBNXXyZvmwGeLqhksWvW4a
  kaigara_token: s.1noBnqFsXR0mbM5Ta5jERAhC
  sonic_token: s.ZUcijXJhO9s8TZrc0sq8FYB7
database:
  host: db
  adapter: mysql
  port: 3306
  user: root
  password: changeme
storage:
  provider: Google
  bucketName: opendax-barong-docs-bucket
  region: fra1
  endpoint: https://fra1.digitaloceanspaces.com
  accessKey: changeme
  secretKey: changeme
  signatureVersion: '2'
twilio:
  enabled: false
  phone_number: "+15005550000"
  account_sid: changeme
  auth_token: changeme
gaTrackerKey: ''
captcha:
  type: none
  siteKey: changeme
  secretKey: changeme
smtp:
  host: smtp.sendgrid.net
  port: 2525
  user: apikey
  password: changeme
  sender_email: noreply@barong.io
  sender_name: Postmaster
  sender_logo: https://storage.googleapis.com/public_peatio/logo.png
wallets:
  eth:
  - kind: deposit
    address: changeme
    max_balance: 0.0
    secret: changeme
  - kind: hot
    address: changeme
    max_balance: 100.0
    secret: changeme
  - kind: warm
    address: changeme
    max_balance: 1000.0
    secret: changeme
  btc:
  - kind: deposit
    address: changeme
    max_balance: 0.0
  - kind: hot
    address: changeme
    max_balance: 100.0
  - kind: warm
    address: changeme
    max_balance: 1000.0
parity:
  network: testnet
  address: parity
  rpcport: 8545
  port: 30303
bitcoind:
  enabled: false
  rpcuser: admin
  rpcpassword: changeme
  address: bitcoind
  network: testnet
  rpcport: 18332
  port: 18333
litecoind:
  rpcuser: admin
  rpcpassword: changeme
  address: litecoind
  network: testnet
  rpcport: 19332
  port: 19335
terraform:
  credentials: "~/safe/opendax.json"
  project: example-opendax
  region: europe-west4
  zone: europe-west4-a
  instance_name: opendax-cloud
  machine_type: n1-standard-4
  image: debian-cloud/debian-9
